[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "canivete_suico_python_toolkit"
version = "0.1.0"
description = "Toolkit Python multifuncional"
requires-python = ">=3.8"
