[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-toolkit"
version = "0.1.0"
description = "Toolkit em Python"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name="Jo√£o Pedro" }
]
